"""add is_pinned to notes

Revision ID: 538214d259fd
Revises: 21f8f5ea5d0e
Create Date: 2026-07-07 11:08:05.167942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538214d259fd'
down_revision: Union[str, Sequence[str], None] = '21f8f5ea5d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_pinned')
    # ### end Alembic commands ###
